# Imports and reading in dataset

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Real_Estate.csv')
df

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,103378.0,for_sale,105000.0,3.0,2.0,0.12,1962661.0,Adjuntas,Puerto Rico,601.0,920.0,NaN
1,52707.0,for_sale,80000.0,4.0,2.0,0.08,1902874.0,Adjuntas,Puerto Rico,601.0,1527.0,NaN
2,103379.0,for_sale,67000.0,2.0,1.0,0.15,1404990.0,Juana Diaz,Puerto Rico,795.0,748.0,NaN
3,31239.0,for_sale,145000.0,4.0,2.0,0.10,1947675.0,Ponce,Puerto Rico,731.0,1800.0,NaN
4,34632.0,for_sale,65000.0,6.0,2.0,0.05,331151.0,Mayaguez,Puerto Rico,680.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,68915.0,for_sale,467847.0,5.0,4.0,0.19,773587.0,Harker Heights,Texas,76548.0,3499.0,NaN
1048571,68915.0,for_sale,345249.0,5.0,3.0,0.19,772323.0,Harker Heights,Texas,76548.0,2572.0,NaN
1048572,61150.0,for_sale,325000.0,NaN,NaN,0.68,1024251.0,Harker Heights,Texas,76548.0,NaN,NaN
1048573,68915.0,for_sale,456122.0,5.0,4.0,0.19,273557.0,Harker Heights,Texas,76548.0,3499.0,NaN
1048574,61150.0,for_sale,325000.0,NaN,NaN,0.69,1024490.0,Harker Heights,Texas,76548.0,NaN,NaN

In [ ]:
GA_real_estate = df[df['state'] == "Georgia"]
GA_real_estate

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
33005,25795.0,for_sale,531625.0,5.0,4.0,NaN,449883.0,Hampton,Georgia,30228.0,3661.0,NaN
33161,25795.0,for_sale,525210.0,5.0,4.0,NaN,451392.0,Hampton,Georgia,30228.0,3661.0,10/31/2022
33162,25795.0,for_sale,490225.0,5.0,3.0,NaN,443887.0,Hampton,Georgia,30228.0,3116.0,10/27/2022
33326,25795.0,for_sale,481705.0,5.0,3.0,NaN,451889.0,Hampton,Georgia,30228.0,3116.0,7/20/2022
74346,90897.0,for_sale,145000.0,NaN,NaN,0.91,330788.0,Lincolnton,Georgia,30817.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
658465,53372.0,for_sale,70000.0,NaN,NaN,NaN,62322.0,Midland,Georgia,31820.0,NaN,NaN
732665,86193.0,for_sale,635000.0,NaN,NaN,1.35,1338694.0,Suwanee,Georgia,30024.0,NaN,5/11/2022
732666,86193.0,for_sale,635000.0,NaN,NaN,0.85,1689061.0,Suwanee,Georgia,30024.0,NaN,NaN
775604,10448.0,for_sale,135000.0,NaN,NaN,2.73,1898469.0,Waverly,Georgia,31565.0,NaN,NaN
900367,46136.0,for_sale,391650.0,5.0,3.0,0.29,621121.0,Columbus,Georgia,31904.0,3151.0,NaN

In [ ]:
GA_real_estate.isna().sum()

brokered_by         107
status                0
price                 6
bed               15811
bath              16337
acre_lot           5311
street               65
city                 23
state                 0
zip_code              7
house_size        20583
prev_sold_date    22722
dtype: int64

In [ ]:
# Seeing as the primary purpose of the project is to find a location that the client finds suitable, we have opted to omit entries where
# locational data was left blank
GA_real_estate = GA_real_estate.dropna(subset = ['street', 'city', 'zip_code'])
GA_real_estate.isna().sum()

brokered_by         106
status                0
price                 6
bed               15762
bath              16287
acre_lot           5305
street                0
city                  0
state                 0
zip_code              0
house_size        20530
prev_sold_date    22653
dtype: int64

In [ ]:
GA_NA_bed_bath = GA_real_estate[GA_real_estate['bed'].isna() | GA_real_estate['bath'].isna()]
len(GA_NA_bed_bath)

16324

In [ ]:
# Upon doing some research, there are various reasons why bed, bath, or both may be left blank. while the most common reason is that
# the listing is for land, rather than a house, there are other reasons, such as an incomplete listing or intentional omission of the
# count. As such, I did not want to simply remove rows where bed or bath hads null values, as this can still provide valuable information
# I instead opted to create a new column to mark these so that the data was not lost, but could be filtered out if desired.

GA_real_estate['Special_property'] = (GA_real_estate['bed'].isna()) | (GA_real_estate['bath'].isna())
GA_real_estate

<ipython-input-19-c7a327973647>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GA_real_estate['Special_property'] = (GA_real_estate['bed'].isna()) | (GA_real_estate['bath'].isna())

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date,Special_property
33005,25795.0,for_sale,531625.0,5.0,4.0,NaN,449883.0,Hampton,Georgia,30228.0,3661.0,NaN,False
33161,25795.0,for_sale,525210.0,5.0,4.0,NaN,451392.0,Hampton,Georgia,30228.0,3661.0,10/31/2022,False
33162,25795.0,for_sale,490225.0,5.0,3.0,NaN,443887.0,Hampton,Georgia,30228.0,3116.0,10/27/2022,False
33326,25795.0,for_sale,481705.0,5.0,3.0,NaN,451889.0,Hampton,Georgia,30228.0,3116.0,7/20/2022,False
74346,90897.0,for_sale,145000.0,NaN,NaN,0.91,330788.0,Lincolnton,Georgia,30817.0,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
658465,53372.0,for_sale,70000.0,NaN,NaN,NaN,62322.0,Midland,Georgia,31820.0,NaN,NaN,True
732665,86193.0,for_sale,635000.0,NaN,NaN,1.35,1338694.0,Suwanee,Georgia,30024.0,NaN,5/11/2022,True
732666,86193.0,for_sale,635000.0,NaN,NaN,0.85,1689061.0,Suwanee,Georgia,30024.0,NaN,NaN,True
775604,10448.0,for_sale,135000.0,NaN,NaN,2.73,1898469.0,Waverly,Georgia,31565.0,NaN,NaN,True
900367,46136.0,for_sale,391650.0,5.0,3.0,0.29,621121.0,Columbus,Georgia,31904.0,3151.0,NaN,False